version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  prepare:
    executor:
      name: android/android-machine
    steps:
      - run:
          name: Write setting file
          command: |
            echo $GRADLE_PROPERTIES > ~/.gradle/gradle.properties
            echo $KEYS_PROPERTIES > keys.properties

  run_test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - android/run-tests:
          test-command: ./gradlew --gradle-user-home ~/.gradle testDebugUnitTest

  release:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Assemble release build
          command: |
            ./gradlew publishReleasePublicationToMavenRepository

workflows:
  pull_request_workflow:
    jobs:
      - prepare
      - run_test:
          requires:
            - prepare

  release_workflow:
    jobs:
      - prepare
      - run_test:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
            - run_test
      - release:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
