version: 2.1

orbs:
  android: circleci/android@1.0.3

commands:
  attach:
    description: "Attach workspace"
    steps:
      - attach_workspace:
          at: ~/project

  setup:
    steps:
      - run:
          name: Write setting file
          command: |
            mkdir ~/.gradle
            echo $KEYS_PROPERTIES | base64 -d > keys.properties
            echo $SIGNING_GRADLE_PROPERTIES | base64 -d >> gradle.properties
            echo $GNUPG_SECRING | base64 -d > furufuru/secring.gpg

jobs:
  run_test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - attach
      - setup
      - android/restore-gradle-cache:
          cache-prefix: test-gradle-v1
      - android/run-tests:
          test-command: ./gradlew --gradle-user-home ~/.gradle testDebugUnitTest
      - android/save-gradle-cache:
          cache-prefix: test-gradle-v1

  release:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - attach
      - setup
      - android/restore-gradle-cache:
          cache-prefix: release-gradle-v1
      - run:
          name: Release to maven repository
          command: |
            ./gradlew publishReleasePublicationToMavenRepository
      - android/save-gradle-cache:
          cache-prefix: release-gradle-v1

workflows:
  pull_request_workflow:
    jobs:
      - run_test:
          filters:
            branches:
              ignore:
                - master

  release_workflow:
    jobs:
      - run_test:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - run_test
      - release:
          requires:
            - hold

