name: release
on:
  workflow_dispatch:

env:
  GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
  PROPERTY_KEYS: ${{ secrets.PROPERTY_KEYS }}
  GRADLE_USER_HOME: ~/.gradle

jobs:
  bintray_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate keys.properties
        run: echo "$PROPERTY_KEYS" > keys.properties

      - name: setup gradle properties
        run: |
          mkdir ~/.gradle/
          echo "${{ env.GRADLE_PROPERTIES }}" > ~/.gradle/gradle.properties
          mkdir .gradle/
          echo "${{ env.GRADLE_PROPERTIES }}" >> furufuru/gradle.properties

      - name: generate gradlew
        run: gradle --gradle-user-home ~/.gradle wrapper

      - name: build and upload
        run: ./gradlew publishReleasePublicationToMavenRepository

